# Generated by Django 4.1.3 on 2023-01-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_online',
            field=models.CharField(blank=True, max_length=100000),
        ),
    ]
