# Generated by Django 4.1.3 on 2023-01-17 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_online',
        ),
    ]
