# Generated by Django 4.1.3 on 2023-01-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('credit_number', models.IntegerField(verbose_name='Credit Number')),
                ('expiration', models.CharField(max_length=5, verbose_name='Expiration')),
                ('security_code', models.IntegerField(verbose_name='Security Code')),
            ],
        ),
    ]
