# Generated by Django 4.1.3 on 2023-01-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='expiration',
            field=models.CharField(max_length=10, verbose_name='Expiration'),
        ),
    ]
