# Generated by Django 4.1.3 on 2023-01-20 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0005_alter_creditcard_expiration_alter_creditcard_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='credit_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='expiration',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='name',
            field=models.CharField(max_length=500000),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='security_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
