# Generated by Django 4.1.3 on 2023-01-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_creditcard_sum_alter_creditcard_credit_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='sum',
            field=models.IntegerField(),
        ),
    ]
