# Generated by Django 4.1.3 on 2023-01-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_creditcard_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='credit_number',
            field=models.CharField(max_length=500000),
        ),
    ]
