# Generated by Django 4.1.3 on 2023-01-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_creditcard_credit_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='status',
            field=models.CharField(choices=[('Sent', 'Sent'), ('Processing', 'Processing'), ('Canceled', 'Canceled')], default='Processing', max_length=10000),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='sum',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
    ]
